version: "3.9"

services:
  api:
    build: ./api
    environment:
      - OFFCLOUD_DATAROOT=/data
    volumes:
    - ./data:/data
    ports:
      - 3000:3000

  api_test:
    build: ./api_test
    environment:
      - OFFCLOUD_BASEURL=http://api:3000
    depends_on:
      - api
