version: "3.9"
services:
  api:
    build: ./api
    volumes:
    - ./api/:/api
    - ./upload/:/api/upload
    ports:
      - 3000:3000
  api_test:
    build: ./api_test
    volumes:
    - ./api_test/:/api_test
    - ./assets/:/api_test/assets
    depends_on:
      - api
  # web:
  #   build: ./web
  #   ports:
  #     - 3001:3001
